package com.foresee.ss.dsp.auto.model;

import java.io.Serializable;

public class SfzjCxjmyzxxError implements Serializable {
    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : XH
     */
    private String xh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : SJLYLX
     */
    private String sjlylx;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : SBJBJG_DM
     */
    private String sbjbjgDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : SB_YZ_XH
     */
    private String sbYzXh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : SB_YZMX_XH
     */
    private String sbYzmxXh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : GRBH
     */
    private String grbh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : GRBH_SW
     */
    private String grbhSw;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : DWBH
     */
    private String dwbh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : DWBH_SW
     */
    private String dwbhSw;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : XZLX_DM
     */
    private String xzlxDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : YJJE
     */
    private String yjje;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : SFSSQ_QSRQ
     */
    private String sfssqQsrq;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : SFSSQ_ZZRQ
     */
    private String sfssqZzrq;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : JK_QX
     */
    private String jkQx;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : YHHB_DM
     */
    private String yhhbDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : YH_ZHKHM
     */
    private String yhZhkhm;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : YH_ZH
     */
    private String yhZh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : ZHBH
     */
    private String zhbh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : QYXYSH
     */
    private String qyxysh;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : BDLX_DM
     */
    private String bdlxDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : DR_SJ
     */
    private String drSj;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : DQ_SJ
     */
    private String dqSj;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : DQJGLX_DM
     */
    private String dqjglxDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : BZ
     */
    private String bz;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : CSPCH
     */
    private String cspch;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : FQNY
     */
    private String fqny;

    /**
     * 表 : T_SFZJ_CXJMYZXX_ERROR
     * 对应字段 : ERROR_MSG
     */
    private String errorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SFZJ_CXJMYZXX_ERROR
     *
     * @MBG Generated Fri Nov 09 11:38:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.XH：null
     */
    public String getXh() {
        return xh;
    }

    /**
     * set method
     *
     * @param xh null
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.SJLYLX：null
     */
    public String getSjlylx() {
        return sjlylx;
    }

    /**
     * set method
     *
     * @param sjlylx null
     */
    public void setSjlylx(String sjlylx) {
        this.sjlylx = sjlylx == null ? null : sjlylx.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.SBJBJG_DM：null
     */
    public String getSbjbjgDm() {
        return sbjbjgDm;
    }

    /**
     * set method
     *
     * @param sbjbjgDm null
     */
    public void setSbjbjgDm(String sbjbjgDm) {
        this.sbjbjgDm = sbjbjgDm == null ? null : sbjbjgDm.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.SB_YZ_XH：null
     */
    public String getSbYzXh() {
        return sbYzXh;
    }

    /**
     * set method
     *
     * @param sbYzXh null
     */
    public void setSbYzXh(String sbYzXh) {
        this.sbYzXh = sbYzXh == null ? null : sbYzXh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.SB_YZMX_XH：null
     */
    public String getSbYzmxXh() {
        return sbYzmxXh;
    }

    /**
     * set method
     *
     * @param sbYzmxXh null
     */
    public void setSbYzmxXh(String sbYzmxXh) {
        this.sbYzmxXh = sbYzmxXh == null ? null : sbYzmxXh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.GRBH：null
     */
    public String getGrbh() {
        return grbh;
    }

    /**
     * set method
     *
     * @param grbh null
     */
    public void setGrbh(String grbh) {
        this.grbh = grbh == null ? null : grbh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.GRBH_SW：null
     */
    public String getGrbhSw() {
        return grbhSw;
    }

    /**
     * set method
     *
     * @param grbhSw null
     */
    public void setGrbhSw(String grbhSw) {
        this.grbhSw = grbhSw == null ? null : grbhSw.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.DWBH：null
     */
    public String getDwbh() {
        return dwbh;
    }

    /**
     * set method
     *
     * @param dwbh null
     */
    public void setDwbh(String dwbh) {
        this.dwbh = dwbh == null ? null : dwbh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.DWBH_SW：null
     */
    public String getDwbhSw() {
        return dwbhSw;
    }

    /**
     * set method
     *
     * @param dwbhSw null
     */
    public void setDwbhSw(String dwbhSw) {
        this.dwbhSw = dwbhSw == null ? null : dwbhSw.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.XZLX_DM：null
     */
    public String getXzlxDm() {
        return xzlxDm;
    }

    /**
     * set method
     *
     * @param xzlxDm null
     */
    public void setXzlxDm(String xzlxDm) {
        this.xzlxDm = xzlxDm == null ? null : xzlxDm.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.YJJE：null
     */
    public String getYjje() {
        return yjje;
    }

    /**
     * set method
     *
     * @param yjje null
     */
    public void setYjje(String yjje) {
        this.yjje = yjje == null ? null : yjje.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.SFSSQ_QSRQ：null
     */
    public String getSfssqQsrq() {
        return sfssqQsrq;
    }

    /**
     * set method
     *
     * @param sfssqQsrq null
     */
    public void setSfssqQsrq(String sfssqQsrq) {
        this.sfssqQsrq = sfssqQsrq == null ? null : sfssqQsrq.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.SFSSQ_ZZRQ：null
     */
    public String getSfssqZzrq() {
        return sfssqZzrq;
    }

    /**
     * set method
     *
     * @param sfssqZzrq null
     */
    public void setSfssqZzrq(String sfssqZzrq) {
        this.sfssqZzrq = sfssqZzrq == null ? null : sfssqZzrq.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.JK_QX：null
     */
    public String getJkQx() {
        return jkQx;
    }

    /**
     * set method
     *
     * @param jkQx null
     */
    public void setJkQx(String jkQx) {
        this.jkQx = jkQx == null ? null : jkQx.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.YHHB_DM：null
     */
    public String getYhhbDm() {
        return yhhbDm;
    }

    /**
     * set method
     *
     * @param yhhbDm null
     */
    public void setYhhbDm(String yhhbDm) {
        this.yhhbDm = yhhbDm == null ? null : yhhbDm.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.YH_ZHKHM：null
     */
    public String getYhZhkhm() {
        return yhZhkhm;
    }

    /**
     * set method
     *
     * @param yhZhkhm null
     */
    public void setYhZhkhm(String yhZhkhm) {
        this.yhZhkhm = yhZhkhm == null ? null : yhZhkhm.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.YH_ZH：null
     */
    public String getYhZh() {
        return yhZh;
    }

    /**
     * set method
     *
     * @param yhZh null
     */
    public void setYhZh(String yhZh) {
        this.yhZh = yhZh == null ? null : yhZh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.ZHBH：null
     */
    public String getZhbh() {
        return zhbh;
    }

    /**
     * set method
     *
     * @param zhbh null
     */
    public void setZhbh(String zhbh) {
        this.zhbh = zhbh == null ? null : zhbh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.QYXYSH：null
     */
    public String getQyxysh() {
        return qyxysh;
    }

    /**
     * set method
     *
     * @param qyxysh null
     */
    public void setQyxysh(String qyxysh) {
        this.qyxysh = qyxysh == null ? null : qyxysh.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.BDLX_DM：null
     */
    public String getBdlxDm() {
        return bdlxDm;
    }

    /**
     * set method
     *
     * @param bdlxDm null
     */
    public void setBdlxDm(String bdlxDm) {
        this.bdlxDm = bdlxDm == null ? null : bdlxDm.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.DR_SJ：null
     */
    public String getDrSj() {
        return drSj;
    }

    /**
     * set method
     *
     * @param drSj null
     */
    public void setDrSj(String drSj) {
        this.drSj = drSj == null ? null : drSj.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.DQ_SJ：null
     */
    public String getDqSj() {
        return dqSj;
    }

    /**
     * set method
     *
     * @param dqSj null
     */
    public void setDqSj(String dqSj) {
        this.dqSj = dqSj == null ? null : dqSj.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.DQJGLX_DM：null
     */
    public String getDqjglxDm() {
        return dqjglxDm;
    }

    /**
     * set method
     *
     * @param dqjglxDm null
     */
    public void setDqjglxDm(String dqjglxDm) {
        this.dqjglxDm = dqjglxDm == null ? null : dqjglxDm.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.BZ：null
     */
    public String getBz() {
        return bz;
    }

    /**
     * set method
     *
     * @param bz null
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.CSPCH：null
     */
    public String getCspch() {
        return cspch;
    }

    /**
     * set method
     *
     * @param cspch null
     */
    public void setCspch(String cspch) {
        this.cspch = cspch == null ? null : cspch.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.FQNY：null
     */
    public String getFqny() {
        return fqny;
    }

    /**
     * set method
     *
     * @param fqny null
     */
    public void setFqny(String fqny) {
        this.fqny = fqny == null ? null : fqny.trim();
    }

    /**
     * get method
     *
     * @return T_SFZJ_CXJMYZXX_ERROR.ERROR_MSG：null
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * set method
     *
     * @param errorMsg null
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", sjlylx=").append(sjlylx);
        sb.append(", sbjbjgDm=").append(sbjbjgDm);
        sb.append(", sbYzXh=").append(sbYzXh);
        sb.append(", sbYzmxXh=").append(sbYzmxXh);
        sb.append(", grbh=").append(grbh);
        sb.append(", grbhSw=").append(grbhSw);
        sb.append(", dwbh=").append(dwbh);
        sb.append(", dwbhSw=").append(dwbhSw);
        sb.append(", xzlxDm=").append(xzlxDm);
        sb.append(", yjje=").append(yjje);
        sb.append(", sfssqQsrq=").append(sfssqQsrq);
        sb.append(", sfssqZzrq=").append(sfssqZzrq);
        sb.append(", jkQx=").append(jkQx);
        sb.append(", yhhbDm=").append(yhhbDm);
        sb.append(", yhZhkhm=").append(yhZhkhm);
        sb.append(", yhZh=").append(yhZh);
        sb.append(", zhbh=").append(zhbh);
        sb.append(", qyxysh=").append(qyxysh);
        sb.append(", bdlxDm=").append(bdlxDm);
        sb.append(", drSj=").append(drSj);
        sb.append(", dqSj=").append(dqSj);
        sb.append(", dqjglxDm=").append(dqjglxDm);
        sb.append(", bz=").append(bz);
        sb.append(", cspch=").append(cspch);
        sb.append(", fqny=").append(fqny);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append("]");
        return sb.toString();
    }
}