package com.foresee.ss.dsp.auto.model;

import com.foresee.ss.dsp.auto.base.model.BaseModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SfzjCxjmgrjcxx extends BaseModel implements Serializable {

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : SHBZH
     */
    private String shbzh;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : ZJLX
     */
    private String zjlx;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : ZJHM
     */
    private String zjhm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : XM
     */
    private String xm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : XB
     */
    private String xb;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : CS_RQ
     */
    private Date csRq;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : GJDQ_DM
     */
    private String gjdqDm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : HJLX_DM
     */
    private String hjlxDm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : HJSZD_DZ
     */
    private String hjszdDz;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : LX_DZ
     */
    private String lxDz;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : YZBM
     */
    private String yzbm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : GDDH
     */
    private String gddh;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : YDDH
     */
    private String yddh;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : EMAIL_DZ
     */
    private String emailDz;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : HJBH
     */
    private String hjbh;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : HZBZ
     */
    private String hzbz;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : BDLX_DM
     */
    private String bdlxDm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : DR_SJ
     */
    private Date drSj;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : DQ_SJ
     */
    private Date dqSj;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : DQJGLX_DM
     */
    private String dqjglxDm;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : BZ
     */
    private String bz;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : CSPCH
     */
    private BigDecimal cspch;

    /**
     * 表 : T_SFZJ_CXJMGRJCXX
     * 对应字段 : FQNY
     */
    private Integer fqny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SFZJ_CXJMGRJCXX
     *
     * @MBG Generated Fri Nov 02 16:37:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.SHBZH：null
     */
    public String getShbzh() {
        return shbzh;
    }

    /**
     * set method 
     *
     * @param shbzh  null
     */
    public void setShbzh(String shbzh) {
        this.shbzh = shbzh == null ? null : shbzh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.ZJLX：null
     */
    public String getZjlx() {
        return zjlx;
    }

    /**
     * set method 
     *
     * @param zjlx  null
     */
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx == null ? null : zjlx.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.ZJHM：null
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * set method 
     *
     * @param zjhm  null
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.XM：null
     */
    public String getXm() {
        return xm;
    }

    /**
     * set method 
     *
     * @param xm  null
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.XB：null
     */
    public String getXb() {
        return xb;
    }

    /**
     * set method 
     *
     * @param xb  null
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.CS_RQ：null
     */
    public Date getCsRq() {
        return csRq;
    }

    /**
     * set method 
     *
     * @param csRq  null
     */
    public void setCsRq(Date csRq) {
        this.csRq = csRq;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.GJDQ_DM：null
     */
    public String getGjdqDm() {
        return gjdqDm;
    }

    /**
     * set method 
     *
     * @param gjdqDm  null
     */
    public void setGjdqDm(String gjdqDm) {
        this.gjdqDm = gjdqDm == null ? null : gjdqDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.HJLX_DM：null
     */
    public String getHjlxDm() {
        return hjlxDm;
    }

    /**
     * set method 
     *
     * @param hjlxDm  null
     */
    public void setHjlxDm(String hjlxDm) {
        this.hjlxDm = hjlxDm == null ? null : hjlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.HJSZD_DZ：null
     */
    public String getHjszdDz() {
        return hjszdDz;
    }

    /**
     * set method 
     *
     * @param hjszdDz  null
     */
    public void setHjszdDz(String hjszdDz) {
        this.hjszdDz = hjszdDz == null ? null : hjszdDz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.LX_DZ：null
     */
    public String getLxDz() {
        return lxDz;
    }

    /**
     * set method 
     *
     * @param lxDz  null
     */
    public void setLxDz(String lxDz) {
        this.lxDz = lxDz == null ? null : lxDz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.YZBM：null
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * set method 
     *
     * @param yzbm  null
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm == null ? null : yzbm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.GDDH：null
     */
    public String getGddh() {
        return gddh;
    }

    /**
     * set method 
     *
     * @param gddh  null
     */
    public void setGddh(String gddh) {
        this.gddh = gddh == null ? null : gddh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.YDDH：null
     */
    public String getYddh() {
        return yddh;
    }

    /**
     * set method 
     *
     * @param yddh  null
     */
    public void setYddh(String yddh) {
        this.yddh = yddh == null ? null : yddh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.EMAIL_DZ：null
     */
    public String getEmailDz() {
        return emailDz;
    }

    /**
     * set method 
     *
     * @param emailDz  null
     */
    public void setEmailDz(String emailDz) {
        this.emailDz = emailDz == null ? null : emailDz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.HJBH：null
     */
    public String getHjbh() {
        return hjbh;
    }

    /**
     * set method 
     *
     * @param hjbh  null
     */
    public void setHjbh(String hjbh) {
        this.hjbh = hjbh == null ? null : hjbh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.HZBZ：null
     */
    public String getHzbz() {
        return hzbz;
    }

    /**
     * set method 
     *
     * @param hzbz  null
     */
    public void setHzbz(String hzbz) {
        this.hzbz = hzbz == null ? null : hzbz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.BDLX_DM：null
     */
    public String getBdlxDm() {
        return bdlxDm;
    }

    /**
     * set method 
     *
     * @param bdlxDm  null
     */
    public void setBdlxDm(String bdlxDm) {
        this.bdlxDm = bdlxDm == null ? null : bdlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.DR_SJ：null
     */
    public Date getDrSj() {
        return drSj;
    }

    /**
     * set method 
     *
     * @param drSj  null
     */
    public void setDrSj(Date drSj) {
        this.drSj = drSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.DQ_SJ：null
     */
    public Date getDqSj() {
        return dqSj;
    }

    /**
     * set method 
     *
     * @param dqSj  null
     */
    public void setDqSj(Date dqSj) {
        this.dqSj = dqSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.DQJGLX_DM：null
     */
    public String getDqjglxDm() {
        return dqjglxDm;
    }

    /**
     * set method 
     *
     * @param dqjglxDm  null
     */
    public void setDqjglxDm(String dqjglxDm) {
        this.dqjglxDm = dqjglxDm == null ? null : dqjglxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.BZ：null
     */
    public String getBz() {
        return bz;
    }

    /**
     * set method 
     *
     * @param bz  null
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.CSPCH：null
     */
    public BigDecimal getCspch() {
        return cspch;
    }

    /**
     * set method 
     *
     * @param cspch  null
     */
    public void setCspch(BigDecimal cspch) {
        this.cspch = cspch;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRJCXX.FQNY：null
     */
    public Integer getFqny() {
        return fqny;
    }

    /**
     * set method 
     *
     * @param fqny  null
     */
    public void setFqny(Integer fqny) {
        this.fqny = fqny;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", grbh=").append(grbh);
        sb.append(", xzqhxqDm=").append(xzqhxqDm);
        sb.append(", sjlylx=").append(sjlylx);
        sb.append(", grbhSw=").append(grbhSw);
        sb.append(", shbzh=").append(shbzh);
        sb.append(", zjlx=").append(zjlx);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", xm=").append(xm);
        sb.append(", xb=").append(xb);
        sb.append(", csRq=").append(csRq);
        sb.append(", gjdqDm=").append(gjdqDm);
        sb.append(", hjlxDm=").append(hjlxDm);
        sb.append(", hjszdDz=").append(hjszdDz);
        sb.append(", lxDz=").append(lxDz);
        sb.append(", yzbm=").append(yzbm);
        sb.append(", gddh=").append(gddh);
        sb.append(", yddh=").append(yddh);
        sb.append(", emailDz=").append(emailDz);
        sb.append(", hjbh=").append(hjbh);
        sb.append(", hzbz=").append(hzbz);
        sb.append(", bdlxDm=").append(bdlxDm);
        sb.append(", drSj=").append(drSj);
        sb.append(", dqSj=").append(dqSj);
        sb.append(", dqjglxDm=").append(dqjglxDm);
        sb.append(", bz=").append(bz);
        sb.append(", cspch=").append(cspch);
        sb.append(", fqny=").append(fqny);
        sb.append("]");
        return sb.toString();
    }
}