package com.foresee.ss.dsp.auto.model;

import com.foresee.ss.dsp.auto.base.model.BaseModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SfzjCxjmyzxx  implements Serializable {
    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : XH
     */
    private String xh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : SJLYLX
     */
    private String sjlylx;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : SBJBJG_DM
     */
    private String sbjbjgDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : SB_YZ_XH
     */
    private String sbYzXh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : SB_YZMX_XH
     */
    private String sbYzmxXh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : GRBH
     */
    private String grbh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : GRBH_SW
     */
    private String grbhSw;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : DWBH
     */
    private String dwbh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : DWBH_SW
     */
    private String dwbhSw;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : XZLX_DM
     */
    private String xzlxDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : YJJE
     */
    private String yjje;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : SFSSQ_QSRQ
     */
    private Date sfssqQsrq;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : SFSSQ_ZZRQ
     */
    private Date sfssqZzrq;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : JK_QX
     */
    private Date jkQx;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : YHHB_DM
     */
    private String yhhbDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : YH_ZHKHM
     */
    private String yhZhkhm;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : YH_ZH
     */
    private String yhZh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : ZHBH
     */
    private String zhbh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : QYXYSH
     */
    private String qyxysh;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : BDLX_DM
     */
    private String bdlxDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : DR_SJ
     */
    private Date drSj;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : DQ_SJ
     */
    private Date dqSj;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : DQJGLX_DM
     */
    private String dqjglxDm;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : BZ
     */
    private String bz;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : CSPCH
     */
    private BigDecimal cspch;

    /**
     * 表 : T_SFZJ_CXJMYZXX
     * 对应字段 : FQNY
     */
    private Integer fqny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SFZJ_CXJMYZXX
     *
     * @MBG Generated Fri Nov 02 16:37:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.XH：null
     */
    public String getXh() {
        return xh;
    }

    /**
     * set method 
     *
     * @param xh  null
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.SJLYLX：null
     */
    public String getSjlylx() {
        return sjlylx;
    }

    /**
     * set method 
     *
     * @param sjlylx  null
     */
    public void setSjlylx(String sjlylx) {
        this.sjlylx = sjlylx == null ? null : sjlylx.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.SBJBJG_DM：null
     */
    public String getSbjbjgDm() {
        return sbjbjgDm;
    }

    /**
     * set method 
     *
     * @param sbjbjgDm  null
     */
    public void setSbjbjgDm(String sbjbjgDm) {
        this.sbjbjgDm = sbjbjgDm == null ? null : sbjbjgDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.SB_YZ_XH：null
     */
    public String getSbYzXh() {
        return sbYzXh;
    }

    /**
     * set method 
     *
     * @param sbYzXh  null
     */
    public void setSbYzXh(String sbYzXh) {
        this.sbYzXh = sbYzXh == null ? null : sbYzXh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.SB_YZMX_XH：null
     */
    public String getSbYzmxXh() {
        return sbYzmxXh;
    }

    /**
     * set method 
     *
     * @param sbYzmxXh  null
     */
    public void setSbYzmxXh(String sbYzmxXh) {
        this.sbYzmxXh = sbYzmxXh == null ? null : sbYzmxXh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.GRBH：null
     */
    public String getGrbh() {
        return grbh;
    }

    /**
     * set method 
     *
     * @param grbh  null
     */
    public void setGrbh(String grbh) {
        this.grbh = grbh == null ? null : grbh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.GRBH_SW：null
     */
    public String getGrbhSw() {
        return grbhSw;
    }

    /**
     * set method 
     *
     * @param grbhSw  null
     */
    public void setGrbhSw(String grbhSw) {
        this.grbhSw = grbhSw == null ? null : grbhSw.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.DWBH：null
     */
    public String getDwbh() {
        return dwbh;
    }

    /**
     * set method 
     *
     * @param dwbh  null
     */
    public void setDwbh(String dwbh) {
        this.dwbh = dwbh == null ? null : dwbh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.DWBH_SW：null
     */
    public String getDwbhSw() {
        return dwbhSw;
    }

    /**
     * set method 
     *
     * @param dwbhSw  null
     */
    public void setDwbhSw(String dwbhSw) {
        this.dwbhSw = dwbhSw == null ? null : dwbhSw.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.XZLX_DM：null
     */
    public String getXzlxDm() {
        return xzlxDm;
    }

    /**
     * set method 
     *
     * @param xzlxDm  null
     */
    public void setXzlxDm(String xzlxDm) {
        this.xzlxDm = xzlxDm == null ? null : xzlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.YJJE：null
     */
    public String getYjje() {
        return yjje;
    }

    /**
     * set method 
     *
     * @param yjje  null
     */
    public void setYjje(String yjje) {
        this.yjje = yjje == null ? null : yjje.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.SFSSQ_QSRQ：null
     */
    public Date getSfssqQsrq() {
        return sfssqQsrq;
    }

    /**
     * set method 
     *
     * @param sfssqQsrq  null
     */
    public void setSfssqQsrq(Date sfssqQsrq) {
        this.sfssqQsrq = sfssqQsrq;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.SFSSQ_ZZRQ：null
     */
    public Date getSfssqZzrq() {
        return sfssqZzrq;
    }

    /**
     * set method 
     *
     * @param sfssqZzrq  null
     */
    public void setSfssqZzrq(Date sfssqZzrq) {
        this.sfssqZzrq = sfssqZzrq;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.JK_QX：null
     */
    public Date getJkQx() {
        return jkQx;
    }

    /**
     * set method 
     *
     * @param jkQx  null
     */
    public void setJkQx(Date jkQx) {
        this.jkQx = jkQx;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.YHHB_DM：null
     */
    public String getYhhbDm() {
        return yhhbDm;
    }

    /**
     * set method 
     *
     * @param yhhbDm  null
     */
    public void setYhhbDm(String yhhbDm) {
        this.yhhbDm = yhhbDm == null ? null : yhhbDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.YH_ZHKHM：null
     */
    public String getYhZhkhm() {
        return yhZhkhm;
    }

    /**
     * set method 
     *
     * @param yhZhkhm  null
     */
    public void setYhZhkhm(String yhZhkhm) {
        this.yhZhkhm = yhZhkhm == null ? null : yhZhkhm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.YH_ZH：null
     */
    public String getYhZh() {
        return yhZh;
    }

    /**
     * set method 
     *
     * @param yhZh  null
     */
    public void setYhZh(String yhZh) {
        this.yhZh = yhZh == null ? null : yhZh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.ZHBH：null
     */
    public String getZhbh() {
        return zhbh;
    }

    /**
     * set method 
     *
     * @param zhbh  null
     */
    public void setZhbh(String zhbh) {
        this.zhbh = zhbh == null ? null : zhbh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.QYXYSH：null
     */
    public String getQyxysh() {
        return qyxysh;
    }

    /**
     * set method 
     *
     * @param qyxysh  null
     */
    public void setQyxysh(String qyxysh) {
        this.qyxysh = qyxysh == null ? null : qyxysh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.BDLX_DM：null
     */
    public String getBdlxDm() {
        return bdlxDm;
    }

    /**
     * set method 
     *
     * @param bdlxDm  null
     */
    public void setBdlxDm(String bdlxDm) {
        this.bdlxDm = bdlxDm == null ? null : bdlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.DR_SJ：null
     */
    public Date getDrSj() {
        return drSj;
    }

    /**
     * set method 
     *
     * @param drSj  null
     */
    public void setDrSj(Date drSj) {
        this.drSj = drSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.DQ_SJ：null
     */
    public Date getDqSj() {
        return dqSj;
    }

    /**
     * set method 
     *
     * @param dqSj  null
     */
    public void setDqSj(Date dqSj) {
        this.dqSj = dqSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.DQJGLX_DM：null
     */
    public String getDqjglxDm() {
        return dqjglxDm;
    }

    /**
     * set method 
     *
     * @param dqjglxDm  null
     */
    public void setDqjglxDm(String dqjglxDm) {
        this.dqjglxDm = dqjglxDm == null ? null : dqjglxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.BZ：null
     */
    public String getBz() {
        return bz;
    }

    /**
     * set method 
     *
     * @param bz  null
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.CSPCH：null
     */
    public BigDecimal getCspch() {
        return cspch;
    }

    /**
     * set method 
     *
     * @param cspch  null
     */
    public void setCspch(BigDecimal cspch) {
        this.cspch = cspch;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMYZXX.FQNY：null
     */
    public Integer getFqny() {
        return fqny;
    }

    /**
     * set method 
     *
     * @param fqny  null
     */
    public void setFqny(Integer fqny) {
        this.fqny = fqny;
    }

    //状态码
    private String code;
    //消息
    private String msg;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", sjlylx=").append(sjlylx);
        sb.append(", sbjbjgDm=").append(sbjbjgDm);
        sb.append(", sbYzXh=").append(sbYzXh);
        sb.append(", sbYzmxXh=").append(sbYzmxXh);
        sb.append(", grbh=").append(grbh);
        sb.append(", grbhSw=").append(grbhSw);
        sb.append(", dwbh=").append(dwbh);
        sb.append(", dwbhSw=").append(dwbhSw);
        sb.append(", xzlxDm=").append(xzlxDm);
        sb.append(", yjje=").append(yjje);
        sb.append(", sfssqQsrq=").append(sfssqQsrq);
        sb.append(", sfssqZzrq=").append(sfssqZzrq);
        sb.append(", jkQx=").append(jkQx);
        sb.append(", yhhbDm=").append(yhhbDm);
        sb.append(", yhZhkhm=").append(yhZhkhm);
        sb.append(", yhZh=").append(yhZh);
        sb.append(", zhbh=").append(zhbh);
        sb.append(", qyxysh=").append(qyxysh);
        sb.append(", bdlxDm=").append(bdlxDm);
        sb.append(", drSj=").append(drSj);
        sb.append(", dqSj=").append(dqSj);
        sb.append(", dqjglxDm=").append(dqjglxDm);
        sb.append(", bz=").append(bz);
        sb.append(", cspch=").append(cspch);
        sb.append(", fqny=").append(fqny);
        sb.append("]");
        return sb.toString();
    }
}