package com.foresee.ss.dsp.auto.model;

import com.foresee.ss.dsp.auto.base.model.BaseModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SfzjCxjmgrcbxx extends BaseModel implements Serializable  {

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : XZLX_DM
     */
    private String xzlxDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : TCQBM_DM
     */
    private String tcqbmDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : SBJBJG_DM
     */
    private String sbjbjgDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : DWBH
     */
    private String dwbh;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : DWBH_SW
     */
    private String dwbhSw;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : XZJD_DM
     */
    private String xzjdDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : SQCBH_DM
     */
    private String sqcbhDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : SCCB_RQ
     */
    private Date sccbRq;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : RYCBBGLX_DM
     */
    private String rycbbglxDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : CBRYTSLB
     */
    private String cbrytslb;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : BDLX_DM
     */
    private String bdlxDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : DR_SJ
     */
    private Date drSj;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : DQ_SJ
     */
    private Date dqSj;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : DQJGLX_DM
     */
    private String dqjglxDm;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : BZ
     */
    private String bz;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : CSPCH
     */
    private BigDecimal cspch;

    /**
     * 表 : T_SFZJ_CXJMGRCBXX
     * 对应字段 : FQNY
     */
    private Integer fqny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SFZJ_CXJMGRCBXX
     *
     * @MBG Generated Fri Nov 02 16:37:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

  /*  *//**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.XH：null
     *//*
    public String getXh() {
        return xh;
    }

    *//**
     * set method 
     *
     * @param xh  null
     *//*
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    *//**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.GRBH：null
     *//*
    public String getGrbh() {
        return grbh;
    }

    *//**
     * set method 
     *
     * @param grbh  null
     *//*
    public void setGrbh(String grbh) {
        this.grbh = grbh == null ? null : grbh.trim();
    }

    *//**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.XZQHXQ_DM：null
     *//*
    public String getXzqhxqDm() {
        return xzqhxqDm;
    }

    *//**
     * set method 
     *
     * @param xzqhxqDm  null
     *//*
    public void setXzqhxqDm(String xzqhxqDm) {
        this.xzqhxqDm = xzqhxqDm == null ? null : xzqhxqDm.trim();
    }

    *//**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.SJLYLX：null
     *//*
    public String getSjlylx() {
        return sjlylx;
    }

    *//**
     * set method 
     *
     * @param sjlylx  null
     *//*
    public void setSjlylx(String sjlylx) {
        this.sjlylx = sjlylx == null ? null : sjlylx.trim();
    }

    *//**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.GRBH_SW：null
     *//*
    public String getGrbhSw() {
        return grbhSw;
    }

    *//**
     * set method 
     *
     * @param grbhSw  null
     *//*
    public void setGrbhSw(String grbhSw) {
        this.grbhSw = grbhSw == null ? null : grbhSw.trim();
    }
*/
    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.XZLX_DM：null
     */
    public String getXzlxDm() {
        return xzlxDm;
    }

    /**
     * set method 
     *
     * @param xzlxDm  null
     */
    public void setXzlxDm(String xzlxDm) {
        this.xzlxDm = xzlxDm == null ? null : xzlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.TCQBM_DM：null
     */
    public String getTcqbmDm() {
        return tcqbmDm;
    }

    /**
     * set method 
     *
     * @param tcqbmDm  null
     */
    public void setTcqbmDm(String tcqbmDm) {
        this.tcqbmDm = tcqbmDm == null ? null : tcqbmDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.SBJBJG_DM：null
     */
    public String getSbjbjgDm() {
        return sbjbjgDm;
    }

    /**
     * set method 
     *
     * @param sbjbjgDm  null
     */
    public void setSbjbjgDm(String sbjbjgDm) {
        this.sbjbjgDm = sbjbjgDm == null ? null : sbjbjgDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.DWBH：null
     */
    public String getDwbh() {
        return dwbh;
    }

    /**
     * set method 
     *
     * @param dwbh  null
     */
    public void setDwbh(String dwbh) {
        this.dwbh = dwbh == null ? null : dwbh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.DWBH_SW：null
     */
    public String getDwbhSw() {
        return dwbhSw;
    }

    /**
     * set method 
     *
     * @param dwbhSw  null
     */
    public void setDwbhSw(String dwbhSw) {
        this.dwbhSw = dwbhSw == null ? null : dwbhSw.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.XZJD_DM：null
     */
    public String getXzjdDm() {
        return xzjdDm;
    }

    /**
     * set method 
     *
     * @param xzjdDm  null
     */
    public void setXzjdDm(String xzjdDm) {
        this.xzjdDm = xzjdDm == null ? null : xzjdDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.SQCBH_DM：null
     */
    public String getSqcbhDm() {
        return sqcbhDm;
    }

    /**
     * set method 
     *
     * @param sqcbhDm  null
     */
    public void setSqcbhDm(String sqcbhDm) {
        this.sqcbhDm = sqcbhDm == null ? null : sqcbhDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.SCCB_RQ：null
     */
    public Date getSccbRq() {
        return sccbRq;
    }

    /**
     * set method 
     *
     * @param sccbRq  null
     */
    public void setSccbRq(Date sccbRq) {
        this.sccbRq = sccbRq;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.RYCBBGLX_DM：null
     */
    public String getRycbbglxDm() {
        return rycbbglxDm;
    }

    /**
     * set method 
     *
     * @param rycbbglxDm  null
     */
    public void setRycbbglxDm(String rycbbglxDm) {
        this.rycbbglxDm = rycbbglxDm == null ? null : rycbbglxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.CBRYTSLB：null
     */
    public String getCbrytslb() {
        return cbrytslb;
    }

    /**
     * set method 
     *
     * @param cbrytslb  null
     */
    public void setCbrytslb(String cbrytslb) {
        this.cbrytslb = cbrytslb == null ? null : cbrytslb.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.BDLX_DM：null
     */
    public String getBdlxDm() {
        return bdlxDm;
    }

    /**
     * set method 
     *
     * @param bdlxDm  null
     */
    public void setBdlxDm(String bdlxDm) {
        this.bdlxDm = bdlxDm == null ? null : bdlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.DR_SJ：null
     */
    public Date getDrSj() {
        return drSj;
    }

    /**
     * set method 
     *
     * @param drSj  null
     */
    public void setDrSj(Date drSj) {
        this.drSj = drSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.DQ_SJ：null
     */
    public Date getDqSj() {
        return dqSj;
    }

    /**
     * set method 
     *
     * @param dqSj  null
     */
    public void setDqSj(Date dqSj) {
        this.dqSj = dqSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.DQJGLX_DM：null
     */
    public String getDqjglxDm() {
        return dqjglxDm;
    }

    /**
     * set method 
     *
     * @param dqjglxDm  null
     */
    public void setDqjglxDm(String dqjglxDm) {
        this.dqjglxDm = dqjglxDm == null ? null : dqjglxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.BZ：null
     */
    public String getBz() {
        return bz;
    }

    /**
     * set method 
     *
     * @param bz  null
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.CSPCH：null
     */
    public BigDecimal getCspch() {
        return cspch;
    }

    /**
     * set method 
     *
     * @param cspch  null
     */
    public void setCspch(BigDecimal cspch) {
        this.cspch = cspch;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMGRCBXX.FQNY：null
     */
    public Integer getFqny() {
        return fqny;
    }

    /**
     * set method 
     *
     * @param fqny  null
     */
    public void setFqny(Integer fqny) {
        this.fqny = fqny;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", grbh=").append(grbh);
        sb.append(", xzqhxqDm=").append(xzqhxqDm);
        sb.append(", sjlylx=").append(sjlylx);
        sb.append(", grbhSw=").append(grbhSw);
        sb.append(", xzlxDm=").append(xzlxDm);
        sb.append(", tcqbmDm=").append(tcqbmDm);
        sb.append(", sbjbjgDm=").append(sbjbjgDm);
        sb.append(", dwbh=").append(dwbh);
        sb.append(", dwbhSw=").append(dwbhSw);
        sb.append(", xzjdDm=").append(xzjdDm);
        sb.append(", sqcbhDm=").append(sqcbhDm);
        sb.append(", sccbRq=").append(sccbRq);
        sb.append(", rycbbglxDm=").append(rycbbglxDm);
        sb.append(", cbrytslb=").append(cbrytslb);
        sb.append(", bdlxDm=").append(bdlxDm);
        sb.append(", drSj=").append(drSj);
        sb.append(", dqSj=").append(dqSj);
        sb.append(", dqjglxDm=").append(dqjglxDm);
        sb.append(", bz=").append(bz);
        sb.append(", cspch=").append(cspch);
        sb.append(", fqny=").append(fqny);
        sb.append("]");
        return sb.toString();
    }
}