package com.foresee.ss.dsp.auto.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 两居虚拟户单位信息交换接口
 */
public class SfzjCxjmxnhjcxx implements Serializable {
    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : XH
     */
    private String xh;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : DWBH
     */
    private String dwbh;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : DWMC
     */
    private String dwmc;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : XZQHXQ_DM
     */
    private String xzqhxqDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : SJLYLX
     */
    private String sjlylx;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : DWBH_SW
     */
    private String dwbhSw;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : SHXYDM
     */
    private String shxydm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : ZZJG_DM
     */
    private String zzjgDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : SBJBJG_DM
     */
    private String sbjbjgDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : SBTCJC_DM
     */
    private String sbtcjcDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : XZJD_DM
     */
    private String xzjdDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : LX_DZ
     */
    private String lxDz;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : LXDH
     */
    private String lxdh;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : JBR_MC
     */
    private String jbrMc;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : JBRSFZJZL_DM
     */
    private String jbrsfzjzlDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : BSRSFZJHM
     */
    private String bsrsfzjhm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : BSY_DH
     */
    private String bsyDh;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : BDLX_DM
     */
    private String bdlxDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : DR_SJ
     */
    private Date drSj;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : DQ_SJ
     */
    private Date dqSj;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : DQJGLX_DM
     */
    private String dqjglxDm;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : BZ
     */
    private String bz;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : CSPCH
     */
    private BigDecimal cspch;

    /**
     * 表 : T_SFZJ_CXJMXNHJCXX
     * 对应字段 : FQNY
     */
    private Integer fqny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SFZJ_CXJMXNHJCXX
     *
     * @MBG Generated Fri Nov 02 16:37:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.XH：null
     */
    public String getXh() {
        return xh;
    }

    /**
     * set method 
     *
     * @param xh  null
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.DWBH：null
     */
    public String getDwbh() {
        return dwbh;
    }

    /**
     * set method 
     *
     * @param dwbh  null
     */
    public void setDwbh(String dwbh) {
        this.dwbh = dwbh == null ? null : dwbh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.DWMC：null
     */
    public String getDwmc() {
        return dwmc;
    }

    /**
     * set method 
     *
     * @param dwmc  null
     */
    public void setDwmc(String dwmc) {
        this.dwmc = dwmc == null ? null : dwmc.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.XZQHXQ_DM：null
     */
    public String getXzqhxqDm() {
        return xzqhxqDm;
    }

    /**
     * set method 
     *
     * @param xzqhxqDm  null
     */
    public void setXzqhxqDm(String xzqhxqDm) {
        this.xzqhxqDm = xzqhxqDm == null ? null : xzqhxqDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.SJLYLX：null
     */
    public String getSjlylx() {
        return sjlylx;
    }

    /**
     * set method 
     *
     * @param sjlylx  null
     */
    public void setSjlylx(String sjlylx) {
        this.sjlylx = sjlylx == null ? null : sjlylx.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.DWBH_SW：null
     */
    public String getDwbhSw() {
        return dwbhSw;
    }

    /**
     * set method 
     *
     * @param dwbhSw  null
     */
    public void setDwbhSw(String dwbhSw) {
        this.dwbhSw = dwbhSw == null ? null : dwbhSw.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.SHXYDM：null
     */
    public String getShxydm() {
        return shxydm;
    }

    /**
     * set method 
     *
     * @param shxydm  null
     */
    public void setShxydm(String shxydm) {
        this.shxydm = shxydm == null ? null : shxydm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.ZZJG_DM：null
     */
    public String getZzjgDm() {
        return zzjgDm;
    }

    /**
     * set method 
     *
     * @param zzjgDm  null
     */
    public void setZzjgDm(String zzjgDm) {
        this.zzjgDm = zzjgDm == null ? null : zzjgDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.SBJBJG_DM：null
     */
    public String getSbjbjgDm() {
        return sbjbjgDm;
    }

    /**
     * set method 
     *
     * @param sbjbjgDm  null
     */
    public void setSbjbjgDm(String sbjbjgDm) {
        this.sbjbjgDm = sbjbjgDm == null ? null : sbjbjgDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.SBTCJC_DM：null
     */
    public String getSbtcjcDm() {
        return sbtcjcDm;
    }

    /**
     * set method 
     *
     * @param sbtcjcDm  null
     */
    public void setSbtcjcDm(String sbtcjcDm) {
        this.sbtcjcDm = sbtcjcDm == null ? null : sbtcjcDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.XZJD_DM：null
     */
    public String getXzjdDm() {
        return xzjdDm;
    }

    /**
     * set method 
     *
     * @param xzjdDm  null
     */
    public void setXzjdDm(String xzjdDm) {
        this.xzjdDm = xzjdDm == null ? null : xzjdDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.LX_DZ：null
     */
    public String getLxDz() {
        return lxDz;
    }

    /**
     * set method 
     *
     * @param lxDz  null
     */
    public void setLxDz(String lxDz) {
        this.lxDz = lxDz == null ? null : lxDz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.LXDH：null
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * set method 
     *
     * @param lxdh  null
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.JBR_MC：null
     */
    public String getJbrMc() {
        return jbrMc;
    }

    /**
     * set method 
     *
     * @param jbrMc  null
     */
    public void setJbrMc(String jbrMc) {
        this.jbrMc = jbrMc == null ? null : jbrMc.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.JBRSFZJZL_DM：null
     */
    public String getJbrsfzjzlDm() {
        return jbrsfzjzlDm;
    }

    /**
     * set method 
     *
     * @param jbrsfzjzlDm  null
     */
    public void setJbrsfzjzlDm(String jbrsfzjzlDm) {
        this.jbrsfzjzlDm = jbrsfzjzlDm == null ? null : jbrsfzjzlDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.BSRSFZJHM：null
     */
    public String getBsrsfzjhm() {
        return bsrsfzjhm;
    }

    /**
     * set method 
     *
     * @param bsrsfzjhm  null
     */
    public void setBsrsfzjhm(String bsrsfzjhm) {
        this.bsrsfzjhm = bsrsfzjhm == null ? null : bsrsfzjhm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.BSY_DH：null
     */
    public String getBsyDh() {
        return bsyDh;
    }

    /**
     * set method 
     *
     * @param bsyDh  null
     */
    public void setBsyDh(String bsyDh) {
        this.bsyDh = bsyDh == null ? null : bsyDh.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.BDLX_DM：null
     */
    public String getBdlxDm() {
        return bdlxDm;
    }

    /**
     * set method 
     *
     * @param bdlxDm  null
     */
    public void setBdlxDm(String bdlxDm) {
        this.bdlxDm = bdlxDm == null ? null : bdlxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.DR_SJ：null
     */
    public Date getDrSj() {
        return drSj;
    }

    /**
     * set method 
     *
     * @param drSj  null
     */
    public void setDrSj(Date drSj) {
        this.drSj = drSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.DQ_SJ：null
     */
    public Date getDqSj() {
        return dqSj;
    }

    /**
     * set method 
     *
     * @param dqSj  null
     */
    public void setDqSj(Date dqSj) {
        this.dqSj = dqSj;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.DQJGLX_DM：null
     */
    public String getDqjglxDm() {
        return dqjglxDm;
    }

    /**
     * set method 
     *
     * @param dqjglxDm  null
     */
    public void setDqjglxDm(String dqjglxDm) {
        this.dqjglxDm = dqjglxDm == null ? null : dqjglxDm.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.BZ：null
     */
    public String getBz() {
        return bz;
    }

    /**
     * set method 
     *
     * @param bz  null
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.CSPCH：null
     */
    public BigDecimal getCspch() {
        return cspch;
    }

    /**
     * set method 
     *
     * @param cspch  null
     */
    public void setCspch(BigDecimal cspch) {
        this.cspch = cspch;
    }

    /**
     * get method 
     *
     * @return T_SFZJ_CXJMXNHJCXX.FQNY：null
     */
    public Integer getFqny() {
        return fqny;
    }

    /**
     * set method 
     *
     * @param fqny  null
     */
    public void setFqny(Integer fqny) {
        this.fqny = fqny;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xh=").append(xh);
        sb.append(", dwbh=").append(dwbh);
        sb.append(", dwmc=").append(dwmc);
        sb.append(", xzqhxqDm=").append(xzqhxqDm);
        sb.append(", sjlylx=").append(sjlylx);
        sb.append(", dwbhSw=").append(dwbhSw);
        sb.append(", shxydm=").append(shxydm);
        sb.append(", zzjgDm=").append(zzjgDm);
        sb.append(", sbjbjgDm=").append(sbjbjgDm);
        sb.append(", sbtcjcDm=").append(sbtcjcDm);
        sb.append(", xzjdDm=").append(xzjdDm);
        sb.append(", lxDz=").append(lxDz);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", jbrMc=").append(jbrMc);
        sb.append(", jbrsfzjzlDm=").append(jbrsfzjzlDm);
        sb.append(", bsrsfzjhm=").append(bsrsfzjhm);
        sb.append(", bsyDh=").append(bsyDh);
        sb.append(", bdlxDm=").append(bdlxDm);
        sb.append(", drSj=").append(drSj);
        sb.append(", dqSj=").append(dqSj);
        sb.append(", dqjglxDm=").append(dqjglxDm);
        sb.append(", bz=").append(bz);
        sb.append(", cspch=").append(cspch);
        sb.append(", fqny=").append(fqny);
        sb.append("]");
        return sb.toString();
    }
}